name: Mon CI

on:
  push:
    branches: [main, feature-readme]   # exécute sur push vers ces branches
 
  pull_request:
    branches: [main, feature-readme]

jobs:
  construction:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Vérifications
        run: |
          echo "✅ Félicitations, Pipeline CI déclenché avec réussite"
          ls -l
